load('//:subdir_glob.bzl', 'subdir_glob')

cxx_library(
  name = 'ui',
  header_namespace = 'ui',
  srcs = [
    'stxsavedialog.c',
    'stxconfig.c',
    'stxnumberfield.c'
  ],
  exported_headers = subdir_glob([
    ('headers', '**/*.h')
  ]),
  deps = [
    '//external/gtkmm-2.0:gtkmm-2.0'
  ],
  visibility = ['PUBLIC']
)
