load('//:buckaroo_macros.bzl', 'buckaroo_deps')
load('//:subdir_glob.bzl', 'subdir_glob')

cxx_library(
  name = 'stx',
  compiler_flags = [
    '-fpermissive'
  ],
  srcs = [
    'read.cpp',
    'write.cpp',
    'bytes.cpp'
  ],
  header_namespace = 'stx',
  exported_headers = subdir_glob([
    ('headers', '**/*.h')
  ]),
  deps = [
    '//external/gimp-2.0:gimp-2.0'
  ] + buckaroo_deps(),
  visibility = ['PUBLIC']
)
